
import { Category, Order, OrderStatus, Product, Translation, RoleDef, User, Permission, LocationDef, Customer } from "./types";

export const TRANSLATIONS: Translation = {
  // General
  dashboard: { en: "Dashboard", fr: "Tableau de bord" },
  inventory: { en: "Inventory", fr: "Inventaire" },
  orders: { en: "Orders", fr: "Commandes" },
  customers: { en: "Customers", fr: "Clients" },
  finance: { en: "Finance & Forecast", fr: "Finance et Prévisions" },
  abandonedCarts: { en: "Abandoned Carts", fr: "Paniers Abandonnés" },
  settings: { en: "Settings", fr: "Paramètres" },
  logout: { en: "Logout", fr: "Déconnexion" },

  // Dashboard Stats
  totalSales: { en: "Total Sales", fr: "Ventes Totales" },
  activeOrders: { en: "Active Orders", fr: "Commandes Actives" },
  lowStock: { en: "Low Stock Items", fr: "Stock Faible" },
  revenue: { en: "Revenue", fr: "Revenus" },
  aiAssistant: { en: "AI Assistant", fr: "Assistant IA" },
  askAi: { en: "Ask Gemini about your business...", fr: "Demandez à Gemini..." },

  // Product & Actions
  addProduct: { en: "Add Product", fr: "Ajouter Produit" },
  generateDesc: { en: "Generate Description with AI", fr: "Générer Description avec IA" },
  uploadImage: { en: "Upload Image", fr: "Télécharger Image" },
  editImage: { en: "Edit with AI", fr: "Modifier avec IA" },
  applyEdit: { en: "Apply Edit", fr: "Appliquer" },
  editPlaceholder: { en: "e.g., Remove background, add brightness...", fr: "ex: Enlever le fond, éclaircir..." },
  processing: { en: "Processing...", fr: "Traitement..." },
  analyzing: { en: "Analyzing...", fr: "Analyse en cours..." },
  save: { en: "Save", fr: "Enregistrer" },
  cancel: { en: "Cancel", fr: "Annuler" },
  delete: { en: "Delete", fr: "Supprimer" },
  edit: { en: "Edit", fr: "Modifier" },

  // Table Headers
  status: { en: "Status", fr: "Statut" },
  customer: { en: "Customer", fr: "Client" },
  total: { en: "Total", fr: "Total" },
  date: { en: "Date", fr: "Date" },
  actions: { en: "Actions", fr: "Actions" },
  category: { en: "Category", fr: "Catégorie" },
  price: { en: "Price", fr: "Prix" },
  stock: { en: "Stock", fr: "Stock" },
  unit: { en: "Unit", fr: "Unité" },
  payment: { en: "Payment", fr: "Paiement" },
  description: { en: "Description", fr: "Description" },
  productName: { en: "Product Name", fr: "Nom du produit" },
  search: { en: "Search...", fr: "Rechercher..." },

  // Customer Stats & Fields
  totalSpent: { en: "Total Spent", fr: "Total Dépensé" },
  totalOrders: { en: "Total Orders", fr: "Commandes Totales" },
  lastOrder: { en: "Last Order", fr: "Dernière Commande" },
  refunded: { en: "Refunded", fr: "Remboursé" },
  refundOrder: { en: "Refund Order", fr: "Rembourser" },
  orderHistory: { en: "Order History", fr: "Historique des Commandes" },
  viewProfile: { en: "View Profile", fr: "Voir Profil" },
  backToCustomers: { en: "Back to Customers", fr: "Retour aux Clients" },
  customerProfile: { en: "Customer Profile", fr: "Profil Client" },
  firstName: { en: "First Name", fr: "Prénom" },
  lastName: { en: "Last Name", fr: "Nom" },
  email: { en: "Email", fr: "Email" },
  phone: { en: "Phone", fr: "Téléphone" },
  physicalAddress: { en: "Physical Address", fr: "Adresse Physique" },
  editCustomer: { en: "Edit Customer", fr: "Modifier Client" },

  // Notifications
  notifications: { en: "Notifications", fr: "Notifications" },
  newOrder: { en: "New Order", fr: "Nouvelle Commande" },
  lowStockAlert: { en: "Low Stock Alert", fr: "Alerte Stock Faible" },
  paymentConfirmed: { en: "Payment Confirmed", fr: "Paiement Confirmé" },
  markRead: { en: "Mark all read", fr: "Tout marquer comme lu" },
  noNotifications: { en: "No notifications", fr: "Aucune notification" },

  // Workflow
  verifyPayment: { en: "Verify Payment", fr: "Vérifier Paiement" },
  processOrder: { en: "Process Order", fr: "Traiter Commande" },
  shipOrder: { en: "Dispatch Order", fr: "Expédier Commande" },
  markDelivered: { en: "Confirm Delivery", fr: "Confirmer Livraison" },
  awaitingCustomerReceipt: { en: "Awaiting customer receipt", fr: "En attente de réception client" },
  cancellationRequested: { en: "Cancellation requested by customer", fr: "Annulation demandée par le client" },
  cancellationApproveHint: { en: "Use \"Cancel Order\" to approve.", fr: "Utilisez « Annuler Commande » pour approuver." },
  cancelOrder: { en: "Cancel Order", fr: "Annuler Commande" },
  accessDenied: { en: "Access Denied", fr: "Accès Refusé" },
  accessDeniedMsg: { en: "You do not have permission to view this page.", fr: "Vous n'avez pas la permission de voir cette page." },

  // Labelling
  sku: { en: "SKU / Label", fr: "SKU / Étiquette" },
  printLabel: { en: "Print Label", fr: "Imprimer Étiquette" },
  labelPreview: { en: "Label Preview", fr: "Aperçu de l'étiquette" },
  print: { en: "Print", fr: "Imprimer" },
  close: { en: "Close", fr: "Fermer" },
  adjustStock: { en: "Adjust Stock", fr: "Ajuster Stock" },

  // Settings & Access Control
  manageCategories: { en: "Manage Categories", fr: "Gérer les Catégories" },
  addCategory: { en: "Add Category", fr: "Ajouter Catégorie" },
  categoryName: { en: "Category Name", fr: "Nom de la catégorie" },
  deleteCategoryWarn: { en: "Are you sure you want to delete this category?", fr: "Êtes-vous sûr de vouloir supprimer cette catégorie ?" },
  cannotDeleteCategory: { en: "Cannot delete category used by products.", fr: "Impossible de supprimer une catégorie utilisée par des produits." },

  accessControl: { en: "Access Control", fr: "Contrôle d'accès" },
  users: { en: "Users", fr: "Utilisateurs" },
  roles: { en: "Roles", fr: "Rôles" },
  general: { en: "General", fr: "Général" },
  addUser: { en: "Add User", fr: "Ajouter Utilisateur" },
  addRole: { en: "Add Role", fr: "Ajouter Rôle" },
  username: { en: "Username", fr: "Nom d'utilisateur" },
  password: { en: "Password", fr: "Mot de passe" },
  role: { en: "Role", fr: "Rôle" },
  permissions: { en: "Permissions", fr: "Permissions" },
  roleName: { en: "Role Name", fr: "Nom du Rôle" },
  editUser: { en: "Edit User", fr: "Modifier Utilisateur" },
  editRole: { en: "Edit Role", fr: "Modifier Rôle" },
  deleteUserWarn: { en: "Are you sure you want to delete this user?", fr: "Êtes-vous sûr de vouloir supprimer cet utilisateur ?" },
  deleteRoleWarn: { en: "Are you sure you want to delete this role?", fr: "Êtes-vous sûr de vouloir supprimer ce rôle ?" },
  loginTitle: { en: "Login to AgriAdmin", fr: "Connexion AgriAdmin" },
  loginBtn: { en: "Login", fr: "Se connecter" },
  invalidCredentials: { en: "Invalid username or password", fr: "Nom d'utilisateur ou mot de passe incorrect" },

  // Profile Management
  myProfile: { en: "My Profile", fr: "Mon Profil" },
  changePassword: { en: "Change Password", fr: "Changer le mot de passe" },
  newPassword: { en: "New Password", fr: "Nouveau mot de passe" },
  profileImage: { en: "Profile Image", fr: "Image de profil" },
  updateProfile: { en: "Update Profile", fr: "Mettre à jour le profil" },
  clickToEditProfile: { en: "Click to edit profile", fr: "Cliquez pour modifier le profil" },

  // Locations Management
  manageLocations: { en: "Manage Locations", fr: "Gérer les lieux" },
  locations: { en: "Locations", fr: "Lieux" },
  city: { en: "City", fr: "Ville" },
  pickupPoint: { en: "Pick-up Point", fr: "Point de retrait" },
  addCity: { en: "Add City", fr: "Ajouter une ville" },
  addPickup: { en: "Add Pick-up Point", fr: "Ajouter un point de retrait" },
  cityName: { en: "City Name", fr: "Nom de la ville" },
  pickupName: { en: "Pick-up Name", fr: "Nom du point" },
  assignLocation: { en: "Assign Location", fr: "Assigner un lieu" },
  directDelivery: { en: "Direct Delivery", fr: "Livraison Directe" },
  pickup: { en: "Pickup", fr: "Retrait" },
  deliveryType: { en: "Delivery Type", fr: "Type de livraison" },
  selectCity: { en: "Select City", fr: "Sélectionner une ville" },
  latitude: { en: "Latitude", fr: "Latitude" },
  longitude: { en: "Longitude", fr: "Longitude" },
  coordinates: { en: "Coordinates", fr: "Coordonnées" },
  locationImage: { en: "Location Image", fr: "Image du lieu" },
  editLocation: { en: "Edit Location", fr: "Modifier le lieu" },
  uploadLocationImage: { en: "Upload Location Image", fr: "Télécharger l'image du lieu" },
  deliveryDetails: { en: "Delivery Details", fr: "Détails de Livraison" },
  openMaps: { en: "Open in Google Maps", fr: "Ouvrir dans Google Maps" },
  noCoords: { en: "No coordinates available", fr: "Pas de coordonnées disponibles" },
  noImage: { en: "No location image available", fr: "Pas d'image de lieu disponible" },

  // Filtering & Calendar
  allOrders: { en: "All Orders", fr: "Toutes les commandes" },
  filterByStatus: { en: "Status", fr: "Statut" },
  filterByLocation: { en: "Location", fr: "Lieu" },
  filterByCategory: { en: "Category", fr: "Catégorie" },
  all: { en: "All", fr: "Tous" },
  active: { en: "Active", fr: "Actif" },
  inactive: { en: "Inactive", fr: "Inactif" },
  clearFilters: { en: "Clear Filters", fr: "Effacer les filtres" },
  searchCustomerPlaceholder: { en: "Search name or phone...", fr: "Rechercher nom ou téléphone..." },
  searchProductPlaceholder: { en: "Search name or label...", fr: "Rechercher nom ou étiquette..." },
  inStock: { en: "In Stock", fr: "En Stock" },
  outOfStock: { en: "Out of Stock", fr: "Rupture de Stock" },
  calendarView: { en: "Calendar View", fr: "Vue Calendrier" },
  listView: { en: "List View", fr: "Vue Liste" },
  scheduledFor: { en: "Scheduled Delivery", fr: "Livraison Prévue" },
  placedOn: { en: "Placed On", fr: "Commandé le" },
  ordersCount: { en: "Orders", fr: "Commandes" },
  day: { en: "Day", fr: "Jour" },
  week: { en: "Week", fr: "Semaine" },
  month: { en: "Month", fr: "Mois" },
  year: { en: "Year", fr: "Année" },
  today: { en: "Today", fr: "Aujourd'hui" },

  // Export & Finance
  export: { en: "Export", fr: "Exporter" },
  exportCSV: { en: "Export CSV", fr: "Exporter CSV" },
  exportExcel: { en: "Export Excel", fr: "Exporter Excel" },
  exportPDF: { en: "Export PDF", fr: "Exporter PDF" },
  previous: { en: "Previous", fr: "Précédent" },
  next: { en: "Next", fr: "Suivant" },
  page: { en: "Page", fr: "Page" },
  of: { en: "of", fr: "sur" },
  track: { en: "Track", fr: "Suivi" },
  forecast: { en: "Forecast", fr: "Prévisions" },
  weekly: { en: "Weekly", fr: "Hebdomadaire" },
  monthly: { en: "Monthly", fr: "Mensuel" },
  yearly: { en: "Yearly", fr: "Annuel" },
  periodRevenue: { en: "Period Revenue", fr: "Revenu Période" },
  growth: { en: "Growth", fr: "Croissance" },
  generateReport: { en: "Generate AI Report", fr: "Générer Rapport IA" },
  financialReport: { en: "Financial Report", fr: "Rapport Financier" },
  projectedRevenue: { en: "Projected Revenue", fr: "Revenu Projeté" },
  printReport: { en: "Print Report", fr: "Imprimer Rapport" },

  // Abandoned Carts
  abandonedCartsTitle: { en: "Abandoned Carts", fr: "Paniers Abandonnés" },
  viewCart: { en: "View Cart", fr: "Voir Panier" },
  followUp: { en: "Follow Up", fr: "Suivi" },
  capturedAt: { en: "Captured At", fr: "Capturé à" },
  lastActive: { en: "Last Active", fr: "Dernier Actif" },
  itemsInCart: { en: "Items in Cart", fr: "Articles" },
  abandonedBy: { en: "Abandoned By", fr: "Abandonné par" },
  noAbandonedCarts: { en: "No abandoned carts found", fr: "Aucun panier abandonné trouvé" },
  deleteCartWarn: { en: "Are you sure you want to remove this abandoned cart?", fr: "Êtes-vous sûr de vouloir supprimer ce panier abandonné ?" },
};

export const ALL_PERMISSIONS: { id: Permission; label: { en: string; fr: string } }[] = [
  { id: 'VIEW_DASHBOARD', label: { en: 'View Dashboard', fr: 'Voir Tableau de bord' } },
  { id: 'VIEW_INVENTORY', label: { en: 'View Inventory', fr: 'Voir Inventaire' } },
  { id: 'MANAGE_INVENTORY', label: { en: 'Manage Inventory', fr: 'Gérer Inventaire' } },
  { id: 'VIEW_ORDERS', label: { en: 'View Orders', fr: 'Voir Commandes' } },
  { id: 'MANAGE_ORDERS', label: { en: 'Manage Orders', fr: 'Gérer Commandes' } },
  { id: 'VIEW_CUSTOMERS', label: { en: 'View Customers', fr: 'Voir Clients' } },
  { id: 'MANAGE_CUSTOMERS', label: { en: 'Manage Customers', fr: 'Gérer Clients' } },
  { id: 'VIEW_FINANCE', label: { en: 'View Finance', fr: 'Voir Finance' } },
  { id: 'VIEW_ABANDONED_CARTS', label: { en: 'View Abandoned Carts', fr: 'Voir Paniers Abandonnés' } },
  { id: 'MANAGE_SETTINGS', label: { en: 'Manage General Settings', fr: 'Gérer Paramètres Généraux' } },
  { id: 'MANAGE_ACCESS_CONTROL', label: { en: 'Manage Users & Roles', fr: 'Gérer Utilisateurs et Rôles' } },
];

export const PRODUCT_UNITS = [
  'Unit',
  'KG',
  'G',
  'Pack',
  'Plastic bag',
  'bottles',
  'Cans',
  'litres',
  'boxes'
];
